# Site settings
title: Bug Shooting
email: mail@bugshooting.com
description: Screen Capture Software for Bug Tracking and Image Sharing
baseurl: "/homepage.github.io"
url: "https://bugshooting.github.io"

docs_url: https://docs.bugshooting.com
translate_url: http://translate.bugshooting.com
download_url: https://services.bugshooting.com/rest/download

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
