# Site settings
title: Bug Shooting
email: mail@bugshooting.com
description: Screen Capture Software for Bug Tracking and Image Sharing

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
